// membuat user
CREATE USER nama_pengguna IDENTIFIED BY kata_sandi;

// Memberikan hak akses SELECT pada tabel tertentu
GRANT SELECT ON nama_tabel TO nama_pengguna;

// Memberikan hak akses INSERT, UPDATE, DELETE pada tabel tertentu
GRANT INSERT, UPDATE, DELETE ON nama_tabel TO nama_pengguna;

// Memberikan hak akses untuk membuat tabel
GRANT CREATE TABLE TO nama_pengguna;

// Memberikan hak akses DBA (Database Administrator)
GRANT DBA TO nama_pengguna;


CREATE TABLE calon_siswa (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nama VARCHAR2(64) NOT NULL,
  alamat VARCHAR2(255) NOT NULL,
  jenis_kelamin VARCHAR2(16) NOT NULL,
  agama VARCHAR2(16) NOT NULL,
  sekolah_asal VARCHAR2(64) NOT NULL
);